/**
 * 兼容层：旧路径仍可 import，实现已迁到 @/lib/repositories/tags/tag
 */
export {
  createMemoTag,
  createProjectTag,
  createTag,
  deleteProjectTag,
  deleteTag,
  getMemoTags,
  getProjectTagById,
  getProjectTags,
  getTagById,
  getTagIdsByEntity,
  getTagIdsByProjectId,
  getTags,
  getTagsByEntity,
  getTagsByEntityIds,
  getTagsByIds,
  getTagsByProjectId,
  getTagsByProjectIds,
  isMemoTagNameDuplicate,
  isProjectTagNameDuplicate,
  isTagNameDuplicate,
  normalizeTagDomain,
  setEntityTagIds,
  setHabitTagIds,
  setMemoTagIds,
  setProjectTagIds,
  setTaskTagIds,
  softDeleteProjectTagLinksForProject,
  softDeleteTagLinksForEntity,
  updateProjectTag,
  updateTag,
} from '../tags/tag';
