import { StyleSheet } from 'react-native';

import { Layout, Radius, Spacing } from '@/constants/design-tokens';

export const composerStyles = StyleSheet.create({
  container: { flex: 1 },
  flex: { flex: 1 },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.lg,
    paddingHorizontal: Layout.pagePaddingX,
    paddingBottom: Spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  topBarBack: {
    width: Layout.iconButtonSize,
    height: Layout.iconButtonSize,
    borderRadius: Radius.icon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarCenter: { flex: 1, gap: 2, minWidth: 0 },
  topBarSub: { fontSize: 11 },
  topBarCreate: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing['2xl'],
    paddingVertical: Spacing.lg,
    borderRadius: Radius.pill,
    minWidth: 88,
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: Layout.pagePaddingX,
    paddingTop: Spacing['2xl'],
  },
  main: {
    gap: Spacing['4xl'],
    maxWidth: Layout.contentMaxWidth,
    alignSelf: 'center',
    width: '100%',
  },
  composeHero: {
    borderRadius: Radius.sheet,
    borderWidth: StyleSheet.hairlineWidth,
    padding: Spacing['4xl'],
    overflow: 'hidden',
    gap: Spacing.lg,
  },
  heroOrb: { position: 'absolute', borderRadius: 999 },
  heroOrbA: { width: 120, height: 120, top: -36, right: -24 },
  heroOrbB: { width: 80, height: 80, bottom: -20, left: -16 },
  heroTopRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  heroBadge: {
    width: 28,
    height: 28,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composeInput: {
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.8,
    lineHeight: 34,
    padding: 0,
    margin: 0,
    minHeight: 68,
  },
  composeFooter: { flexDirection: 'row', alignItems: 'center', gap: Spacing.lg },
  progressTrack: { flex: 1, height: 6, borderRadius: Radius.pill, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: Radius.pill },
  section: { gap: Spacing.lg },
  sectionHead: { flexDirection: 'row', alignItems: 'center', gap: Spacing.lg },
  sectionHeadPress: { marginBottom: Spacing.xs },
  sectionAccent: { width: 4, height: 36, borderRadius: Radius.pill },
  sectionDesc: { marginTop: 2 },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xl,
    borderRadius: Radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: Spacing['2xl'],
    paddingVertical: Spacing['2xl'],
  },
  optionCardBody: { flex: 1, gap: Spacing.xs },
  schedulePanel: {
    flexDirection: 'row',
    gap: Spacing['2xl'],
    borderRadius: Radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    padding: Spacing['2xl'],
    alignItems: 'stretch',
  },
  calendarTile: {
    width: 88,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.lg,
    gap: 2,
  },
  calendarMonth: { fontSize: 12, fontWeight: '800' },
  calendarDay: { fontSize: 32, fontWeight: '900', letterSpacing: -1, lineHeight: 36 },
  calendarEmpty: { marginTop: Spacing.xs, textAlign: 'center' },
  scheduleCopy: { flex: 1, gap: Spacing.sm, justifyContent: 'center' },
  scheduleChips: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md, marginTop: Spacing.xs },
  scheduleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.pill,
    maxWidth: '48%',
  },
  scheduleChipGhost: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderStyle: 'dashed',
  },
  editorialCard: {
    borderRadius: Radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    padding: Spacing['4xl'],
  },
  notePanel: {
    borderRadius: Radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderLeftWidth: 3,
    padding: Spacing['2xl'],
    paddingLeft: Spacing['3xl'],
    minHeight: 120,
    position: 'relative',
  },
  noteQuoteIcon: { position: 'absolute', top: Spacing.lg, left: Spacing.lg, opacity: 0.35 },
  noteInput: { minHeight: 96, lineHeight: 22, paddingTop: Spacing.sm },
  matrixBoard: {
    borderRadius: Radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  matrixHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  matrixRowLabelSlot: { width: 40 },
  matrixAxis: { flex: 1, textAlign: 'center', fontWeight: '800' },
  matrixGridRow: { flexDirection: 'row', alignItems: 'stretch', gap: Spacing.md },
  matrixRowLabel: { width: 40, fontWeight: '800', textAlign: 'right', lineHeight: 16, alignSelf: 'center' },
  matrixCell: {
    flex: 1,
    minHeight: 88,
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
  },
  matrixCellLabel: { fontSize: 12, lineHeight: 16, textAlign: 'center' },
  matrixCellHint: { fontSize: 10, textAlign: 'center' },
  modalOverlay: { flex: 1, justifyContent: 'center', paddingHorizontal: Layout.pagePaddingX },
  modalCard: { borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius['2xl'], padding: Spacing['4xl'], gap: Spacing.md },
  modalTitle: { marginBottom: Spacing.xs },
  modalItem: {
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
});
